# Generated by Django 6.0.2 on 2026-06-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Shop this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='location.location'),
        ),
    ]
