# Generated by Django 6.0.2 on 2026-06-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
        ('products', '0002_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Scannable Barcode (UPC, EAN, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Internal Stock Keeping Unit', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('location', 'sku'), name='uniq_product_sku_per_location'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('location', 'barcode'), name='uniq_product_barcode_per_location'),
        ),
    ]
