# Generated by Django 6.0.2 on 2026-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_barcode_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lowest tier — price for distributors / resellers', max_digits=12, null=True),
        ),
    ]
