# Generated by Django 6.0.2 on 2026-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='is_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
