# Generated by Django 6.0.2 on 2026-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salepayment_is_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price_tier',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('DISTRIBUTOR', 'Distributor')], db_index=True, default='RETAIL', max_length=20),
        ),
    ]
