# Generated by Django 6.0.2 on 2026-10-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_price_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_ref',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='register_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.registersession'),
        ),
    ]
