# Generated by Django 6.0.2 on 2026-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_location_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='backup_phone',
            field=models.CharField(blank=True, help_text='Second number to reach them on.', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Trading name, for distributors and businesses.', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Who to speak to at the company.', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_distributor',
            field=models.BooleanField(db_index=True, default=False, help_text='Buys at the distributor price list and appears on the Distributors page.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
